apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:masters
      rolearn: arn:aws:iam::137253451221:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-24T08:46:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "929"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ea29a8bd-2629-11ea-9618-0e1f93827864
